name: CI

on:
  push:
    branches: [ "CI_CD" ]
  pull_request:
    branches: [ "CI_CD" ]
  workflow_dispatch:
  schedule:
    # Runs every day at midnight
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          postman login --with-api-key ${{ secrets.API_KEY }}
          postman collection run "postman/collections/Herokuapp.json" -e "m_e.json"
